### ISSUE TITLE
Massive crash when Inventor is not installed

### ISSUE THREAD

**Issue by ChrisTerBeke** [thopiekar/CuraInventorPlugin#3]
```
2017-11-29 11:43:32,140 - INFO - CuraInventorPlugin.CadIntegrationUtils.ComFactory.<module> [11]: Python version: sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
2017-11-29 11:43:32,140 - DEBUG - CuraInventorPlugin.CadIntegrationUtils.ComFactory.<module> [14]: Found 3rd-party directory and adding in into PYTHONPATH.
2017-11-29 11:43:32,167 - ERROR - UM.Logger.logException [76]: Exception: Import error loading module CuraInventorPlugin
2017-11-29 11:43:32,232 - CRITICAL - cura.CrashHandler.__init__ [62]: An uncaught exception has occurred!
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 6890: invalid start byte

Original exception was:
Traceback (most recent call last):
  File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraInventorPlugin\CuraInventorPlugin\CadIntegrationUtils\ComFactory\__init__.py", line 28, in <module>
    from .PyWin32Connector import ComConnector
  File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraInventorPlugin\CuraInventorPlugin\CadIntegrationUtils\ComFactory\PyWin32Connector.py", line 7, in <module>
    import win32com
  File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraInventorPlugin\CuraInventorPlugin\CadIntegrationUtils\ComFactory\..\3rd-party\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\msys64\home\c.terbeke\code\github\Uranium\UM\PluginRegistry.py", line 472, in _findPlugin
    module = imp.load_module(plugin_id, file, path, desc)
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\imp.py", line 244, in load_module
    return load_package(name, filename)
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraInventorPlugin\CuraInventorPlugin\__init__.py", line 12, in <module>
    from . import InventorReader
  File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraInventorPlugin\CuraInventorPlugin\InventorReader.py", line 23, in <module>
  File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraInventorPlugin\CuraInventorPlugin\CadIntegrationUtils\CommonComReader.py", line 14, in <module>
    from .ComFactory import ComConnector
  File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraInventorPlugin\CuraInventorPlugin\CadIntegrationUtils\ComFactory\__init__.py", line 31, in <module>
    from .ComTypesConnector import ComConnector
  File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraInventorPlugin\CuraInventorPlugin\CadIntegrationUtils\ComFactory\ComTypesConnector.py", line 4, in <module>
    import comtypes # @UnusedImport
ModuleNotFoundError: No module named 'comtypes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/msys64/home/c.terbeke/code/github/Cura/cura_app.py", line 82, in <module>
    app = cura.CuraApplication.CuraApplication.getInstance()
  File "C:\msys64\home\c.terbeke\code\github\Uranium\UM\Application.py", line 326, in getInstance
    Application._instance = cls()
  File "C:\msys64\home\c.terbeke\code\github\Cura\cura\CuraApplication.py", line 209, in __init__
    tray_icon_name = "cura-icon-32.png")
  File "C:\msys64\home\c.terbeke\code\github\Uranium\UM\Qt\QtApplication.py", line 120, in __init__
    self._loadPlugins()
  File "C:\msys64\home\c.terbeke\code\github\Cura\cura\CuraApplication.py", line 556, in _loadPlugins
    self._plugin_registry.loadPlugins()
  File "C:\msys64\home\c.terbeke\code\github\Uranium\UM\PluginRegistry.py", line 261, in loadPlugins
    plugin_data = self.getMetaData(plugin_id)
  File "C:\msys64\home\c.terbeke\code\github\Uranium\UM\PluginRegistry.py", line 282, in getMetaData
    if not self._populateMetaData(plugin_id):
  File "C:\msys64\home\c.terbeke\code\github\Uranium\UM\PluginRegistry.py", line 386, in _populateMetaData
    plugin = self._findPlugin(plugin_id)
  File "C:\msys64\home\c.terbeke\code\github\Uranium\UM\PluginRegistry.py", line 474, in _findPlugin
    Logger.logException("e", "Import error loading module %s", plugin_id)
  File "C:\msys64\home\c.terbeke\code\github\Uranium\UM\Logger.py", line 79, in logException
    for line in traceback.format_exc().rstrip().split("\n"):
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\traceback.py", line 163, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\traceback.py", line 117, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\traceback.py", line 497, in __init__
    capture_locals=capture_locals)
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\traceback.py", line 358, in extract
    f.line
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\traceback.py", line 282, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "C:\Users\c.terbeke\AppData\Local\Programs\Python\Python36\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 6890: invalid start byte
```

**Comment by thopiekar** [comment]
`ImportError: DLL load failed: The specified module could not be found.`
Seems to be the same issue, like I had in the SolidWorks plugin. Updating CIU should fix it.
Only difference I had was that Cura was not dramatically crashing like this.

**Comment by thopiekar** [comment]
@ChrisTerBeke: Should be fixed now, see https://community.ultimaker.com/topic/21489-autodesk-inventor-plugin-013/?do=findComment&comment=200039

**Comment by ChrisTerBeke** [comment]
@appestijn we can re-test this I guess?
